---
- hosts: localhost
  tasks:  
    - name: Obtain SSO token with using username/password credentials
      ovirt_auth:
        url: ***************
        username: admin@internal
        password: *******
        insecure: true
    - name: Create VM with cloud init
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        name: ansibel
        template: Ansible_Prov
        cluster: Host
        memory: 2
        high_availability: false
        stateless:  false      
        wait: true
        cloud_init:
          nic_boot_protocol: static
          nic_ip_address: 10.0.4.45 
          nic_netmask: 255.255.255.0
          nic_gateway: 10.0.4.1
          nic_name: eth0
          dns_servers: 
          dns_search: 
          nic_on_boot: true
          host_name: ansibllele
    - pause: 
        minutes: 5
